import { vi } from 'vitest';

function asyncFn<T>(value: T) {
  return vi.fn().mockResolvedValue(value);
}

export function createWindowApiMocks() {
  return {
    authApi: {
      setAccessToken: asyncFn(undefined),
      isE2EModeAllowed: asyncFn(false),
    },
    workspaceApi: {
      create: asyncFn({}),
      listMine: asyncFn([]),
      switchActive: asyncFn(undefined),
      invite: asyncFn({}),
      acceptInvite: asyncFn({}),
      revokeInvite: asyncFn(undefined),
      members: {
        list: asyncFn([]),
        updateRole: asyncFn({}),
        remove: asyncFn(undefined),
      },
      getActiveContext: asyncFn(null),
      ensurePersonalWorkspace: asyncFn({ id: 'workspace-1', name: 'Workspace' }),
      update: asyncFn({}),
      delete: asyncFn(undefined),
      leave: asyncFn(undefined),
    },
    hostsApi: {
      list: asyncFn([]),
      getPassword: asyncFn(null),
      create: asyncFn({}),
      update: asyncFn({}),
      delete: asyncFn(undefined),
      moveToFolder: asyncFn({}),
    },
    foldersApi: {
      list: asyncFn([]),
      create: asyncFn({}),
      update: asyncFn({}),
      delete: asyncFn(undefined),
    },
    sshApi: {
      connect: asyncFn(undefined),
      disconnect: asyncFn(undefined),
      send: asyncFn(undefined),
      resize: asyncFn(undefined),
      listKnownHosts: asyncFn([]),
      removeKnownHost: asyncFn(true),
      listHostKeyEvents: asyncFn([]),
      clearHostKeyEvents: asyncFn(undefined),
      onData: vi.fn().mockReturnValue(() => {}),
      onClosed: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
    sftpApi: {
      list: asyncFn([]),
      listLocal: asyncFn([]),
      download: asyncFn(undefined),
      upload: asyncFn(undefined),
      cancel: asyncFn(undefined),
      mkdir: asyncFn(undefined),
      rename: asyncFn(undefined),
      delete: asyncFn(undefined),
      chmod: asyncFn(undefined),
      onProgress: vi.fn().mockReturnValue(() => {}),
      pickUploadFiles: asyncFn(null),
      getSaveFilePath: asyncFn(null),
    },
    keysApi: {
      list: asyncFn([]),
      import: asyncFn({}),
      delete: asyncFn(undefined),
      exportPublic: asyncFn(null),
      syncEncrypted: asyncFn(undefined),
      isWorkspaceEncryptionInitialized: asyncFn(false),
      initializeWorkspaceEncryption: asyncFn(undefined),
      verifyWorkspacePassphrase: asyncFn(false),
      syncKeyToCloud: asyncFn(undefined),
      downloadKeyFromCloud: asyncFn(''),
      deleteKeyFromCloud: asyncFn(undefined),
      changeWorkspacePassphrase: asyncFn(undefined),
    },
    aiApi: {
      complete: asyncFn(undefined),
      translateCommand: asyncFn(undefined),
      onChunk: vi.fn().mockReturnValue(() => {}),
      onDone: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
    agentApi: {
      startRun: asyncFn({}),
      approveStep: asyncFn({}),
      rejectStep: asyncFn({}),
      cancelRun: asyncFn({}),
      chat: asyncFn({}),
      getRun: asyncFn({}),
      listRuns: asyncFn([]),
      runPlaybook: asyncFn({}),
      savePlaybook: asyncFn({}),
      listPlaybooks: asyncFn([]),
      onRunUpdated: vi.fn().mockReturnValue(() => {}),
      onStepOutput: vi.fn().mockReturnValue(() => {}),
      onMessageChunk: vi.fn().mockReturnValue(() => {}),
      onMessageDone: vi.fn().mockReturnValue(() => {}),
      onBlocked: vi.fn().mockReturnValue(() => {}),
      onDone: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
    settingsApi: {
      get: asyncFn({
        id: '',
        userId: '',
        theme: 'dark',
        terminalFont: 'JetBrains Mono',
        terminalFontSize: 13,
        terminalTheme: 'dracula',
        promptStyle: 'default',
        scrollbackLines: 10000,
        cursorStyle: 'block',
        bellStyle: 'none',
        lineHeight: 1,
        copyOnSelect: false,
        aiProvider: 'gemini',
        updatedAt: new Date().toISOString(),
      }),
      update: asyncFn({
        id: '',
        userId: '',
        theme: 'dark',
        terminalFont: 'JetBrains Mono',
        terminalFontSize: 13,
        terminalTheme: 'dracula',
        promptStyle: 'default',
        scrollbackLines: 10000,
        cursorStyle: 'block',
        bellStyle: 'none',
        lineHeight: 1,
        copyOnSelect: false,
        aiProvider: 'gemini',
        updatedAt: new Date().toISOString(),
      }),
    },
    apiKeysApi: {
      get: asyncFn(null),
      set: asyncFn(undefined),
      delete: asyncFn(undefined),
    },
    snippetsApi: {
      list: asyncFn([]),
      create: asyncFn({}),
      update: asyncFn({}),
      delete: asyncFn(undefined),
    },
    recordingApi: {
      start: asyncFn(undefined),
      stop: asyncFn(null),
      list: asyncFn([]),
      read: asyncFn(''),
      isRecording: asyncFn(false),
    },
    updaterApi: {
      checkForUpdates: asyncFn(undefined),
      downloadUpdate: asyncFn(undefined),
      installAndRestart: asyncFn(undefined),
      onUpdateAvailable: vi.fn().mockReturnValue(() => {}),
      onUpdateNotAvailable: vi.fn().mockReturnValue(() => {}),
      onDownloadProgress: vi.fn().mockReturnValue(() => {}),
      onUpdateDownloaded: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
  } as const;
}
